source 'https://github.com/xiaochuanxu/FFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'FFAuthorKits_Example' do
  pod 'FFAuthorKits', :path => '../'

  target 'FFAuthorKits_Tests' do
    inherit! :search_paths

    
  end
end
